export const DOCTOR_PROFILE_CREATE_REQUEST = 'DOCTOR_PROFILE_CREATE_REQUEST';
export const DOCTOR_PROFILE_CREATE_SUCCESS = 'DOCTOR_PROFILE_CREATE_SUCCESS';
export const DOCTOR_PROFILE_CREATE_FAIL = 'DOCTOR_PROFILE_CREATE_FAIL';

export const DOCTOR_PROFILE_REQUEST = 'DOCTOR_PROFILE_REQUEST';
export const DOCTOR_PROFILE_SUCCESS = 'DOCTOR_PROFILE_SUCCESS';
export const DOCTOR_PROFILE_FAIL = 'DOCTOR_PROFILE_FAIL';

export const DOCTOR_PROFILE_UPDATE_REQUEST = 'DOCTOR_PROFILE_UPDATE_REQUEST';
export const DOCTOR_PROFILE_UPDATE_SUCCESS = 'DOCTOR_PROFILE_UPDATE_SUCCESS';
export const DOCTOR_PROFILE_UPDATE_FAIL = 'DOCTOR_PROFILE_UPDATE_FAIL';
