export const DOCTOR_PUBLIC_LIST_REQUEST = 'DOCTOR_PUBLIC_LIST_REQUEST';
export const DOCTOR_PUBLIC_LIST_SUCCESS = 'DOCTOR_PUBLIC_LIST_SUCCESS';
export const DOCTOR_PUBLIC_LIST_FAIL = 'DOCTOR_PUBLIC_LIST_FAIL';
