export const PATIENT_PROFILE_REQUEST = 'PATIENT_PROFILE_REQUEST'
export const PATIENT_PROFILE_SUCCESS = 'PATIENT_PROFILE_SUCCESS'
export const PATIENT_PROFILE_FAIL = 'PATIENT_PROFILE_FAIL'

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST'
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS'
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL'

export const PATIENT_CREATE_REQUEST = 'PATIENT_CREATE_REQUEST'
export const PATIENT_CREATE_SUCCESS = 'PATIENT_CREATE_SUCCESS'
export const PATIENT_CREATE_FAIL = 'PATIENT_CREATE_FAIL'

export const MEDICAL_HISTORY_UPDATE_REQUEST = 'MEDICAL_HISTORY_UPDATE_REQUEST'
export const MEDICAL_HISTORY_UPDATE_SUCCESS = 'MEDICAL_HISTORY_UPDATE_SUCCESS'
export const MEDICAL_HISTORY_UPDATE_FAIL = 'MEDICAL_HISTORY_UPDATE_FAIL'

export const EHR_UPDATE_REQUEST = 'EHR_UPDATE_REQUEST'
export const EHR_UPDATE_SUCCESS = 'EHR_UPDATE_SUCCESS'
export const EHR_UPDATE_FAIL = 'EHR_UPDATE_FAIL'
