export const PATIENT_PRESCRIPTIONS_REQUEST = 'PATIENT_PRESCRIPTIONS_REQUEST';
export const PATIENT_PRESCRIPTIONS_SUCCESS = 'PATIENT_PRESCRIPTIONS_SUCCESS';
export const PATIENT_PRESCRIPTIONS_FAIL = 'PATIENT_PRESCRIPTIONS_FAIL';
